rules:
  - id: odoo-avoid_hardcoded_config_TESTING
    message: Hardcoded variable `TESTING` detected. Use environment variables or
      config files instead
    severity: WARNING
    metadata:
      likelihood: LOW
      impact: LOW
      confidence: LOW
      category: security
      cwe:
        - "CWE-489: Active Debug Code"
      owasp:
        - A05:2021 - Security Misconfiguration
      references:
        - https://bento.dev/checks/flask/avoid-hardcoded-config/
        - https://flask.palletsprojects.com/en/1.1.x/config/?highlight=configuration#builtin-configuration-values
        - https://flask.palletsprojects.com/en/1.1.x/config/?highlight=configuration#environment-and-debug-features
      subcategory:
        - audit
      technology:
        - flask
      license: Commons Clause License Condition v1.0[LGPL-2.1-only]
    languages:
      - python
    pattern-either:
      - pattern: $M.config['TESTING'] = True
      - pattern: $M.config['TESTING'] = False
      - pattern: $M.update(TESTING=True, ...)
      - pattern: $M.update(TESTING=False, ...)
