rules:
  - id: odoo-avoid_hardcoded_config_ENV
    message: Hardcoded variable `ENV` detected. Set this by using FLASK_ENV
      environment variable
    severity: WARNING
    metadata:
      likelihood: LOW
      impact: LOW
      confidence: LOW
      category: security
      cwe:
        - "CWE-489: Active Debug Code"
      owasp:
        - A05:2021 - Security Misconfiguration
      references:
        - https://bento.dev/checks/flask/avoid-hardcoded-config/
        - https://flask.palletsprojects.com/en/1.1.x/config/?highlight=configuration#builtin-configuration-values
        - https://flask.palletsprojects.com/en/1.1.x/config/?highlight=configuration#environment-and-debug-features
      subcategory:
        - audit
      technology:
        - flask
      license: Commons Clause License Condition v1.0[LGPL-2.1-only]
    languages:
      - python
    pattern-either:
      - pattern: $M.update(ENV="=~/^development|production$/")
      - pattern: $M.config['ENV'] = "=~/^development|production$/"
      - patterns : 
        - pattern: $M.update(ENV="=~/^development|production$/")
        - pattern: $M.config['ENV'] = "=~/^development|production$/"
